### PR TITLE
fix: added agency id check to remove agency button in agency table

### LINKED ISSUE #66: [ID Tool] Agency staff should not be able to see unassignment buttons to unassign other agencies
In the grant modal window, agency staff members are currently able to see the trash bin icons that imply that they are able to unassign the grant from other agencies.

In this example, the user is a staff member of the "Administration: Fleet Services Division" agency.

CleanShot 2022-04-26 at 13 20 48@2x

They should not be able to see the bottom 3 trash bin buttons.

(For what it's worth, when they are pressed, nothing happens, which is the correct behavior. I presume there is a backend authorization check.)

### PR DESCRIPTION
**Pull request by davidbkay**
easy fix added a check in the grants modal to only show delete button if the row's agency_id value matched the user's agency.id.

Closes #66

### CODE REVIEW

File: packages/client/src/components/Modals/GrantDetails.vue [hunk 1]
```diff
@@ -92,7 +92,7 @@
         :fields="assignedAgenciesFields"
       >
       <template #cell(actions)="row">
-        <b-button variant="danger" class="mr-1" size="sm" @click="unassignAgenciesToGrant(row)">
+        <b-button v-if="row.item.agency_id === agency.id" variant="danger" class="mr-1" size="sm" @click="unassignAgenciesToGrant(row)">
```
Comment (mattbroussard) [inline packages/client/src/components/Modals/GrantDetails.vue:95]: I think this should check for membership in `agencies` -- any agency I can assign to I should be able to unassign from, I think (i.e. subagencies of my selected agency).

What if I accidentally assigned to an agency other than my own? As written I don't think this would let me unassign it even if I'm an admin who can change my `selectedAgency` to that agency.

**Review by mattbroussard — CHANGES_REQUESTED** [review]

File: packages/client/src/components/Modals/GrantDetails.vue (hunk 1 above)
Comment (Rapol) [reply packages/client/src/components/Modals/GrantDetails.vue:95]: Correct. The /session returns user information which has the agency the user belongs. We can use user.agency.subAgencies to determine if the agency is one I have access to. 

But I think the list of agencies we show in the dropdown are already all agencies that i have access to so this wont do anything.

Comment (mhuang-usdr) [reply packages/client/src/components/Modals/GrantDetails.vue:95]: Per #61 - only being able to assign to a subagency is a bug. Any user should be able to assign a grant to any other agency.

It sounds like the concern expressed here is "what happens if I assign something on accident"?

We have a WIP feature on the product/design side for a user to be able to track and manage all the grants they've assigned to someone else slated for the next major milestone. In the meantime, the workaround is for users to communicate to the other agency outside of the tool. It's not great, but it's MVP.

@Raphomet wdyt?

Comment (mhuang-usdr) [reply packages/client/src/components/Modals/GrantDetails.vue:95]: From further discussion in the standup today:

Since we already track the user who assigned grant, let's go ahead and implement what @mattbroussard proposed - 

**any agency user has assigned, they should also be able to unassign**

**Comment by Raphomet** [comment]
fox-jumping

File: packages/server/seeds/dev/ref/users.js [hunk 2]
```diff
@@ -25,7 +25,7 @@ module.exports = [
     },
     {
         id: 2,
-        email: 'mindy@usdigitalresponse.org', // fake email for testing
+        email: 'mhuang@usdigitalresponse.org', // fake email for testing
```
Comment (mattbroussard) [inline packages/server/seeds/dev/ref/users.js:28]: Note this will break some tests that refer to this email; be sure to grep for those and update the email there. See #63 and #67. #67 is to make this type of breakage less likely.

**Comment by mattbroussard** [comment]
@davidbkay it seems like this isn't complete but Github shows it closed/merged since you merged into `staging`. But it's not merged into `main`.

It sounds like there isn't a way to "reopen", so for review on additional changes I think you'll have to open a separate PR off the same branch? https://stackoverflow.com/a/12838195

**Comment by davidbkay** [comment]
Maybe...make the PR for main and just merge it into staging for verification?
