### PR TITLE
fix: validation error when agency is 0

### LINKED ISSUE #616: [Infra/ARPA] On the ARPA tool, we cannot add a user to the USDR agency
image

This works in the ID tool, so there might be a special check that ARPA tool is doing on `agency_id`?

### PR DESCRIPTION
**Pull request by disambiguator**
### Ticket #616 

Fixes #616 

### Description
Fixes error when agency_id is 0. Since 0 is falsy in JavaScript, we need to explicitly
check for null or undefined.

### CODE REVIEW

File: packages/server/src/arpa_reporter/services/validate-upload.js [hunk 1]
```diff
@@ -650,7 +650,6 @@ async function validateUpload (upload, user, trns = null) {
 
 module.exports = {
   validateUpload,
-  ValidationError
```
Comment (disambiguator) [inline packages/server/src/arpa_reporter/services/validate-upload.js:653]: unrelated fix, but this is an unused export

**Review by as1729 — APPROVED** [review]
Thanks for doing this!

File: packages/server/src/arpa_reporter/routes/users.js [hunk 2]
```diff
@@ -20,7 +20,7 @@ async function validateUser (user, creator) {
     throw new Error('Role required')
   }
 
-  if (!agency_id) {
+  if (agency_id == null) {
```
Comment (as1729) [inline packages/server/src/arpa_reporter/routes/users.js:23]: @disambiguator can we add some test coverage around this as well? I noticed late that there wasn't unit tests around this. Since this function us sed by many endpoints it should help improve overall repo coverage.
